# Generated by Django 3.2.9 on 2021-11-10 16:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=16384)),
                ('haveBan', models.BooleanField(default=False)),
                ('color', models.CharField(default='#ccc', max_length=16)),
                ('countLikes', models.IntegerField()),
                ('countDislikes', models.IntegerField()),
                ('dateCreate', models.TimeField(default=datetime.datetime(2021, 11, 10, 16, 13, 47, 330933, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32, null=True)),
                ('haveBan', models.BooleanField(default=False)),
                ('color', models.CharField(default='#ccc', max_length=16)),
                ('dateRegistration', models.TimeField(default=datetime.datetime(2021, 11, 10, 16, 13, 47, 329932, tzinfo=utc))),
                ('idRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.role')),
            ],
        ),
        migrations.CreateModel(
            name='TagAndArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.article')),
                ('idTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.tag')),
            ],
        ),
        migrations.CreateModel(
            name='LikeOrDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('idArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.article')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('idArticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.article')),
                ('idUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyrsah.user'),
        ),
    ]
