# Generated by Django 3.2.9 on 2021-11-26 17:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0003_auto_20211123_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='countDislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='countLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='dateCreate',
            field=models.TimeField(default=datetime.datetime(2021, 11, 26, 17, 43, 30, 86394, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateRegistration',
            field=models.TimeField(default=datetime.datetime(2021, 11, 26, 17, 43, 30, 85392, tzinfo=utc)),
        ),
    ]
