# Generated by Django 3.2.9 on 2021-12-05 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0004_auto_20211126_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dateCreate',
            field=models.TimeField(default=datetime.datetime(2021, 12, 5, 7, 2, 39, 233553, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateRegistration',
            field=models.DateTimeField(default=datetime.date(2021, 12, 5)),
        ),
    ]
