# Generated by Django 3.2.9 on 2021-12-05 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0005_auto_20211205_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='dateCreate',
        ),
    ]
