# Generated by Django 3.2.9 on 2021-12-05 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0006_remove_article_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.date(2021, 12, 5)),
        ),
    ]
