# Generated by Django 3.2.9 on 2021-12-07 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0007_article_datecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='dateCreate',
            field=models.DateTimeField(default=datetime.date(2021, 12, 7)),
        ),
        migrations.AlterField(
            model_name='user',
            name='dateRegistration',
            field=models.DateTimeField(default=datetime.date(2021, 12, 7)),
        ),
    ]
