# Generated by Django 3.2.9 on 2021-12-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0008_auto_20211207_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagandarticle',
            name='idArticle',
        ),
        migrations.RemoveField(
            model_name='tagandarticle',
            name='idTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagAndArticle',
        ),
    ]
