# Generated by Django 3.2.9 on 2021-12-07 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrsah', '0009_auto_20211207_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dateRegistration',
            field=models.DateField(default=datetime.date(2021, 12, 7)),
        ),
    ]
